services:
  abiotic-server:
    build: .
    restart: unless-stopped
    volumes:
      - "./gamefiles:/server"
      - "./data:/server/AbioticFactor/Saved"
    environment:
      - MaxServerPlayers=6
      - Port=7777
      - QueryPort=27015
      - ServerPassword=${SERVER_PASSWORD:-}
      - SteamServerName=${SERVER_NAME:-Abiotic Factor Server}
      - UsePerfThreads=true
      - NoAsyncLoadingThread=true
      - WorldSaveName=${WORLD_SAVE_NAME:-Cascade}
      - AutoUpdate=${AUTO_UPDATE:-false}
      # - AdditionalArgs=-SandboxIniPath=Config/WindowsServer/Server1Sandbox.ini
    ports:
      - "7777:7777/udp"
      - "27015:27015/udp"