name: Test Abiotic Factor Server Setup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-setup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Test Docker build
      run: |
        docker build -t abfactor-test .
        
    - name: Test Docker Compose configuration
      run: |
        docker compose config
        
    - name: Test Makefile commands
      run: |
        make help
        
    - name: Lint Dockerfile
      run: |
        docker run --rm -i hadolint/hadolint < Dockerfile
